name: E2E Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: â¬‡ï¸ Checkout Code
          uses: actions/checkout@v4

        - name: ğŸ¢ Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            node-version-file: '.nvmrc' #optional

        - name: ğŸ—ï¸ Install Dependencies
          run: npm install

        - name: ğŸ”“ Fix wdio permissions
          run: chmod +x ./node_modules/.bin/wdio

        - name: ğŸ§ª Test
          run: npm run wdio

        - name: ğŸ”“ Fix wdio permissions
          run: chmod +x ./node_modules/.bin/allure
          run: chmod +x ./node_modules/allure-commandline/dist/bin/allure

        - name: ğŸ“Š Generate Allure Report
          run: npx allure generate ./allure-results --clean -o ./allure-report
 
        # - name: ğŸ“¦ Upload Logs
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: allureReport
        #     path: ./allure-report
